### ISSUE TITLE
Command-line imagick tools

### ISSUE THREAD

**Issue by indietravel** [Chassis/Imagick#3]
Hi, using this extension and I can see it's in place; same settings as my live env, which is a win :)

```
$ php --info | grep imagick
/etc/php/7.0/cli/conf.d/20-imagick.ini,
imagick
imagick module => enabled
imagick module version => 3.4.3
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
imagick.locale_fix => 0 => 0
imagick.progress_monitor => 0 => 0
imagick.skip_version_check => 1 => 1
```

However, I can't access any of the cli tools, for example:
```
$ identify
-bash: identify: command not found
```
In production, this would spout all the usage notes. 

Is there something else needed in this extension to be able to use command-line Image Magick tools?

**Comment by indietravel** [comment]
I had to `sudo apt-get install imagemagick` inside the VM (e.g. inside `vagrant ssh`) to get this working. Not familiar enough with how everything works to be able to submit a patch, I'm afraid; but hopefully this will help others until one is available.

**Comment by BronsonQuick** [comment]
@indietravel Thanks so much for the bug report! I hadn't realised I'd missed the CLI tools. I've just updated the extension so those will be installed automatically now.
